new files

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,5 +1,3 @@
-name: Deployment
-
 on:
   push:
     branches:
@@ -14,32 +12,38 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Display Approval Message
-        run: |
-          echo "Please review and approve this deployment."
-          echo "To approve, set the 'approved' output to 'true' using '::set-output name=approved::true'"
-          echo "To reject, set the 'approved' output to 'false' using '::set-output name=approved::false'"
-
-      - name: Wait for Approval
+      - name: Verify Approver
         id: verify_approver
-        uses: actions/github-script@v4
-   
+        run: echo "::set-output name=approved::${{ github.actor == 'mutuwa99' }}"
+
+      - name: Manual Approval
+        if: steps.verify_approver.outputs.approved == 'false'
+        run: |
+          echo "Manual approval required. Please approve or reject this deployment."
+          echo "To approve, add a comment on the associated issue: ${{ github.event.issue.html_url }}"
+          echo "To reject, add a comment starting with 'Reject' on the associated issue: ${{ github.event.issue.html_url }}"
+          exit 1
 
   deploy-production:
     name: Deploy to Production Environment
     runs-on: ubuntu-latest
     needs: manual-approval
-    # if: github.ref == 'refs/heads/master' && needs.manual-approval.outputs.approved == 'true'
+#     if: github.ref == 'refs/heads/master' && needs.manual-approval.outputs.approved == 'true'
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      # Add necessary steps to build and prepare your application for deployment
+
       - name: Deploy to Production Environment
-        uses: appleboy/scp-action@v2
+        uses: webfactory/ssh-agent@v0.5.1
         with:
           host: ${{ secrets.SERVER_IP_ADDRESS }}
           username: ${{ secrets.SERVER_USERNAME }}
-          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
-          port: ${{ secrets.SERVER_SSH_PORT }}
-          source: ./
-          target: /var/www/html/
+          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
+          script: |
+            # Change to the appropriate directory on the remote server
+            cd /var/www/html
+
+            # Copy the application files from the GitHub Actions workspace to the remote server
+            cp -r $GITHUB_WORKSPACE/* .
